#!/usr/bin/env python3
"""Exact permutation tests and convergence windows for the dial chapter.

    python scripts/dial_inference.py

Writes thesis/tables/dial/perm.tex and thesis/tables/dial/windows.tex from the
executed records. Epoch labels are the thesis convention: index i is epoch i+1,
so the analysis window is epochs 81--100.
"""
from __future__ import annotations

import itertools
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import dial_figures as df  # noqa: E402
import evaluate_dial as ed  # noqa: E402
from dial_records import tape_dir  # noqa: E402


def exact_permutation(a, b):
    """Mean difference and exact permutation p-values over all relabellings.

    Returns (mean(a) - mean(b), one-sided p for a difference at least this large,
    two-sided p). Seeds are the unit. The one-sided count includes the observed
    labelling.
    """
    a, b = [float(x) for x in a], [float(x) for x in b]
    obs = sum(a) / len(a) - sum(b) / len(b)
    pool = a + b
    n, one, two, tot = len(a), 0, 0, 0
    for idx in itertools.combinations(range(len(pool)), n):
        chosen = set(idx)
        left = [pool[i] for i in idx]
        right = [pool[i] for i in range(len(pool)) if i not in chosen]
        diff = sum(left) / len(left) - sum(right) / len(right)
        tot += 1
        one += diff >= obs - 1e-12
        two += abs(diff) >= abs(obs) - 1e-12
    return obs, one / tot, two / tot


def _series(root, arm):
    return [df._epoch_series(rec) for _, rec in ed.runs(tape_dir(arm, root))]


def _window_mean(series, idx, start, length):
    stack = np.vstack([s[idx] for s in series])
    return float(np.nanmean(stack[:, start:start + length]))


def windows_table(root):
    arms = [
        ("m2_naive", "naive"),
        ("m2_slow", "slow"),
        ("m2_tbn_matched", "tbn-matched"),
        ("m2_tbn_slow", "tbn-slow"),
        ("m2_shaper_matched", "shaper-matched"),
        ("m2_shaper_slow", "shaper-slow"),
        ("m2_shapellm", "ShapeLLM-style"),
    ]
    rows = []
    for arm, label in arms:
        ser = _series(root, arm)
        for start, length, window in ((60, 20, "61--80"), (80, 20, "81--100")):
            joint = _window_mean(ser, 1, start, length) + _window_mean(ser, 2, start, length)
            rows.append([label, window, f"{_window_mean(ser, 0, start, length):.2f}", f"{joint:.1f}"])
    naive = _series(root, "m2_naive")
    for start, length, window in ((2, 5, "3--7"), (19, 5, "20--24")):
        joint = _window_mean(naive, 1, start, length) + _window_mean(naive, 2, start, length)
        rows.append(["naive", window, f"{_window_mean(naive, 0, start, length):.2f}", f"{joint:.1f}"])
    body = "\n".join(" & ".join(r) + r" \\" for r in rows)
    return (
        "% generated by scripts/dial_inference.py\n"
        "\\begin{table}[ht]\n\\centering\n\\footnotesize\n\\singlespacing\n"
        "\\caption[Survival and joint return by window]{Survival and joint return per episode, mean over seeds. "
        "Chained arms are the uncut tapes. "
        "Epoch numbers follow the thesis: the analysis window is epochs 81--100. "
        "Epochs 3--7 and 20--24 are the naive pair around the budget-matched points "
        "of Section~\\ref{sec:res-budget}.}\n"
        "\\label{tab:windows}\n"
        "\\begin{tabular}{llrr}\n\\toprule\n"
        "Arm & Epochs & Survival & Joint return \\\\\n"
        "\\midrule\n"
        f"{body}\n\\bottomrule\n\\end{{tabular}}\n\\end{{table}}\n"
    )


def _seed_values(root, regime, arm, key):
    out = []
    for _, rec in ed.runs(tape_dir(f"m{regime}_{arm}", root)):
        s = ed.summarise(rec, window=20)
        if not s:
            continue
        if key == "surv":
            out.append(s["survival"])
        elif key == "joint":
            out.append(s["return_per_episode"][0] + s["return_per_episode"][1])
        elif key == "a2":
            out.append(s["return_per_episode"][1])
    return out


def _early_restraint(root, arm, agent=1):
    """Mean restraint over epochs 1--40 (indices 0--39), one number per seed."""
    out = []
    for _, rec in ed.runs(tape_dir(arm, root)):
        ep = np.asarray(rec["epoch"])
        live = ~np.asarray(rec["masked"], dtype=bool)
        q = np.asarray(rec["request_2"] if agent == 1 else rec["request_1"])
        n = int(ep.max()) + 1
        rates = []
        for e in range(min(40, n)):
            m = (ep == e) & live
            if m.any():
                rates.append(float(np.mean(q[m] == 1)))
        out.append(float(np.mean(rates)) if rates else float("nan"))
    return out


def perm_table(root):
    rows_spec = [
        ("2", "naive", "shapellm", "surv", "naive $-$ ShapeLLM-style", "Survival"),
        ("2", "naive", "shapellm", "joint", "naive $-$ ShapeLLM-style", "Joint return"),
        ("2", "naive", "slow", "surv", "naive $-$ slow", "Survival"),
        ("2", "naive", "tbn_matched", "surv", "naive $-$ tbn-matched", "Survival"),
        ("2", "slow", "tbn_slow", "surv", "slow $-$ tbn-slow", "Survival"),
        ("2", "tbn_slow", "shaper_slow", "surv", "tbn-slow $-$ shaper-slow", "Survival"),
        ("2", "tbn_matched", "shaper_matched", "surv", "tbn-matched $-$ shaper-matched", "Survival"),
        ("3", "naive", "slow", "a2", "$m=3$, naive $-$ slow", "Return/ep A2"),
        ("3", "naive", "shapellm", "a2", "$m=3$, naive $-$ ShapeLLM-style", "Return/ep A2"),
    ]
    early = [
        ("m2_tbn_slow", "m2_shaper_slow", "tbn-slow $-$ shaper-slow", "A2 restraint, epochs 1--40"),
        ("m2_tbn_slow", "m2_shapellm", "tbn-slow $-$ ShapeLLM-style", "A2 restraint, epochs 1--40"),
        ("m2_tbn_matched", "m2_shaper_matched", "tbn-matched $-$ shaper-matched", "A2 restraint, epochs 1--40"),
    ]
    lines = []
    for regime, a, b, key, name, metric in rows_spec:
        left, right = _seed_values(root, regime, a, key), _seed_values(root, regime, b, key)
        diff, _, two = exact_permutation(left, right)
        fmt = "{:+.2f}" if key == "surv" else "{:+.1f}"
        lines.append(f"{name} & {metric} & {fmt.format(diff)} & {two:.3f} & {len(left)} v {len(right)} \\\\")
    for a, b, name, metric in early:
        left, right = _early_restraint(root, a), _early_restraint(root, b)
        diff, _, two = exact_permutation(left, right)
        lines.append(f"{name} & {metric} & {diff:+.2f} & {two:.3f} & {len(left)} v {len(right)} \\\\")
    body = "\n".join(lines)
    return (
        "% generated by scripts/dial_inference.py\n"
        "\\begin{table}[ht]\n\\centering\n\\footnotesize\n\\singlespacing\n"
        "\\caption[Exact permutation tests]{Exact permutation tests over seeds, every relabelling, two-sided. "
        "The difference is the mean of the first arm minus the mean of the second. "
        "Survival and return use epochs 81--100. Chained arms are the uncut tapes. "
        "The restraint rows are agent~2's share of living rounds taking~1 over epochs 1--40, "
        "a window chosen after the curves were seen. "
        "Unpaired: seeds share a shock table, but play diverges within the first epochs "
        "(Section~\\ref{sec:lim-seeds}), so seed index is not a block. "
        "Exploratory: these tests were not part of the design. Seeds are the unit.}\n"
        "\\label{tab:perm}\n"
        "\\resizebox{\\textwidth}{!}{%\n"
        "\\begin{tabular}{llrrl}\n\\toprule\n"
        "Contrast & Metric & Difference & Two-sided $p$ & Seeds \\\\\n"
        "\\midrule\n"
        f"{body}\n\\bottomrule\n\\end{{tabular}}}}\n\\end{{table}}\n"
    )


def main():
    root = ROOT / "checkpoints" / "dial"
    out = ROOT / "thesis" / "tables" / "dial"
    (out / "perm.tex").write_text(perm_table(root))
    (out / "windows.tex").write_text(windows_table(root))
    print(f"wrote {out / 'perm.tex'}")
    print(f"wrote {out / 'windows.tex'}")


if __name__ == "__main__":
    main()
